#!/bin/bash
# This is a simple build script and will be executed on your CI system if 
# available.  Otherwise it will execute while your application is stopped
# before the deploy step.  This script gets executed directly, so it
# could be python, php, ruby, etc.

# Activate VirtualEnv in order to use the correct libraries
source $OPENSHIFT_HOMEDIR/python-2.6/virtenv/bin/activate

echo "Executing 'python $OPENSHIFT_REPO_DIR/wsgi/mybooktype/manage.py collectstatic --noinput'"
python $OPENSHIFT_REPO_DIR/wsgi/mybooktype/manage.py collectstatic --noinput
