#!/bin/bash
# This deploy hook gets executed after dependencies are resolved and the
# build hook has been run but before the application has been started back
# up again.  This script gets executed directly, so it could be python, php,
# ruby, etc.

# Activate VirtualEnv in order to use the correct libraries
source $OPENSHIFT_APP_DIR/virtenv/bin/activate

#echo "Executing 'python $OPENSHIFT_REPO_DIR/wsgi/mybooktype/manage.py createsuperuser'"
#python $OPENSHIFT_REPO_DIR/wsgi/mybooktype/manage.py createsuperuser

echo "Executing 'python $OPENSHIFT_REPO_DIR/wsgi/mybooktype/manage.py loaddata documentation_licenses'"
python $OPENSHIFT_REPO_DIR/wsgi/mybooktype/manage.py loaddata documentation_licenses

